#!/bin/sh
# Policy routing for DS918+ dual-NIC ZeroTier gateway.
#
# NOTE: This file is a reference template only. install.sh generates the
# actual copy placed in $DATA_DIR/zerotier-one/setuproutes.sh with your
# real IP/subnet/gateway values substituted. Do not edit this file for
# production — edit the generated copy or re-run install.sh.
#
# Ensures traffic sourced from each LAN subnet exits via the correct NIC
# (symmetric return-path routing), and that the ZeroTier daemon's own
# outbound packets also use the correct egress interface.

IF1="eth0"
IF2="eth1"

IP1="192.168.1.253"     # Container IP on LAN 1  (set by install.sh)
IP2="172.16.0.253"      # Container IP on LAN 2  (set by install.sh)

P1="192.168.1.1"        # Gateway LAN 1           (set by install.sh)
P2="172.16.0.1"         # Gateway LAN 2           (set by install.sh)

P1_NET="192.168.1.0/24"
P2_NET="172.16.0.0/24"

TBL1="ISP_1"
TBL2="ISP_2"

# Flush ALL existing policy rules for these tables before re-adding.
# 'ip rule del table X' removes only ONE matching rule per call, so we loop
# until the command fails (meaning no more rules match) to clear all of them.
while ip rule del table $TBL1 2>/dev/null; do true; done
while ip rule del table $TBL2 2>/dev/null; do true; done

# Subnet return-path rules: traffic sourced from each /24 exits the correct NIC.
ip rule add from $P1_NET table $TBL1 priority 100 2>/dev/null || true
ip rule add from $P2_NET table $TBL2 priority 101 2>/dev/null || true

# Container-IP rules: ZeroTier daemon's own outbound packets (keepalives,
# peer handshakes, planet pings) are sourced from the container IP, not a
# client subnet address, so they need their own explicit rule.
ip rule add from $IP1 table $TBL1 priority 98 2>/dev/null || true
ip rule add from $IP2 table $TBL2 priority 99 2>/dev/null || true

# Per-table routes
ip route replace $P1_NET dev $IF1 src $IP1 table $TBL1 2>/dev/null || true
ip route replace default via $P1 table $TBL1 2>/dev/null || true

ip route replace $P2_NET dev $IF2 src $IP2 table $TBL2 2>/dev/null || true
ip route replace default via $P2 table $TBL2 2>/dev/null || true

# Main table fallback default — required so ZeroTier can reach public roots
# (planets/moons) whose addresses don't match either /24 subnet rule.
ip route replace default via $P1 metric 200 2>/dev/null || true

echo "[setuproutes] Policy routing applied (LAN1=$IF1 $IP1, LAN2=$IF2 $IP2)"
